[package]
name = "vec-strings"
version = "0.1.0"
edition = "2021"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Store any string efficiently in an immutable way."
repository = "https://github.com/NobodyXu/vec-strings"

keywords = ["string", "utilities"]
categories = ["data-structures"]

[dependencies]
